In [11]:
import random
from game import Game, Move, Player
from QPlayer import QPlayer, Environment, train, QLearningAgent

import numpy as np
import pickle 
import os
import zipfile


# Seed value
# Apparently you may use different seed values at each stage
seed_value= 2

# 1. Set the `PYTHONHASHSEED` environment variable at a fixed value
os.environ['PYTHONHASHSEED']=str(seed_value)

# 2. Set the `python` built-in pseudo-random generator at a fixed value
random.seed(seed_value)

# 3. Set the `numpy` pseudo-random generator at a fixed value
np.random.seed(seed_value)

In [2]:
class RandomPlayer(Player):
    def __init__(self) -> None:
        super().__init__()

    def make_move(self, game: 'Game') -> tuple[tuple[int, int], Move]:
        from_pos = (random.randint(0, 4), random.randint(0, 4))
        move = random.choice([Move.TOP, Move.BOTTOM, Move.LEFT, Move.RIGHT])
        return from_pos, move

In [3]:
#player1 = QPlayer()
#player1.agent = train(10000)

#with open('qtable0.pkl', 'wb') as f:
#    pickle.dump(player1.agent.q_table, f)

In [4]:
player1 = QPlayer()
player1.agent = QLearningAgent(epsilon=None)

with zipfile.ZipFile('qtable0.zip', 'r') as zip_ref:
    zip_ref.extractall()
    
with open('qtable0.pkl', 'rb') as f:
    player1.agent.q_table  = pickle.load(f)

In [5]:
len(player1.agent.q_table)

1510368

In [12]:
counter = 0

for i in range(100):
    g = Game()
    g.print()

    env = Environment()
    env.game = g
    player1.env = env

    player2 = RandomPlayer()
    winner = g.play(player1, player2)
    if winner == 0: ##winner ==1 in case we are the second player
        counter+= 1
    g.print()

    print(f'-----------------{i}-winner_id: {winner}-----------------')

print(f"Winner: Player {winner}")
print(counter)
print(player1.agent.usefullness / player1.agent.total)


[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
0
(0, 4) Move.RIGHT
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1  0]]
1
(4, 2) Move.LEFT
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [ 1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1  0]]
0
(4, 4) Move.TOP
[[-1 -1 -1 -1  0]
 [-1 -1 -1 -1 -1]
 [ 1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
1
(0, 1) Move.TOP
[[ 1 -1 -1 -1  0]
 [-1 -1 -1 -1 -1]
 [ 1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
0
(3, 4) Move.RIGHT
[[ 1 -1 -1 -1  0]
 [-1 -1 -1 -1 -1]
 [ 1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1  0]]
1
(0, 2) Move.TOP
[[ 1 -1 -1 -1  0]
 [ 1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1  0]]
0
(1, 0) Move.LEFT
[[ 0  1 -1 -1  0]
 [ 1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1  0]]
1
(2, 0) Move.BOTTOM
[[ 0  1 -1 -1  0]
 [ 1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1  1 -1  0]]
----------------------------

In [6]:
print(len(player1.agent.q_table.keys()))
#print(player1.agent.epsilon.counter)

def p(a):
    score = a[1]
    move = a[0][1]
    board = a[0][0]
    #x = np.zeros((5,5), dtype=int)
    #for i in range(len(board)):
    #    x[i // 5][i % 5] = board[i]

    return 0, move, score
    


1510368


In [7]:
a = [x for x in player1.agent.q_table.items()]

In [8]:
counter = 0
for i in range(len(a)):
    x, move, score = p(a[i])
    if score == 0:
        #print(x, move)
        counter += 1

In [9]:
counter / len(a)

5.2967223881861905e-06